-- alm drikkevarer
items["water"] = {"Vand","", gen("Drik",0,-15),0.5}
items["milk"] = {"Mælk","", gen("Drik",0,-5),0.5}
items["coffee"] = {"Kaffe","", gen("Drik",0,-10),0.2}
items["tea"] = {"Te","", gen("Drik",0,-15),0.2}
items["icetea"] = {"Ice-Tea","", gen("Drik",0,-20), 0.5}
items["orangejuice"] = {"Appelsin juice","", gen("Drik",0,-25),0.5}
items["cocacola"] = {"Coca Cola","", gen("Drik",0,-35),0.3}
items["redbull"] = {"Red Bull","", gen("Drik",0,-40),0.3}
items["lemonade"] = {"Lemonade","", gen("Drik",0,-45),0.3} 
items["7up"] = {"7UP","", gen("Drik",0,-20), 0.5}
items["fanta"] = {"Fanta","", gen("Drik",0,-20), 0.5}
items["cult"] = {"Cult","", gen("Drik",0,-20), 0.5}
items["faxekondi"] = {"Faxekondi","", gen("Drik",0,-20), 0.5}
items["faxekondib"] = {"Faxekondi booster","", gen("Drik",0,-20), 0.5}
items["monster"] = {"Monster","", gen("Drik",0,-20), 0.5}
items["kamillete"] = {"Kamille te","", gen("Drik",0,-20), 0.5}
items["frugtte"] = {"Frugt te","", gen("Drik",0,-20), 0.5} 
items["lakridste"] = {"Lakrids te","", gen("Drik",0,-5), 0.5} 
items["cacao"] = {"Cacao","", gen("Drik",0,-5), 0.5} 
items["multijuice"] = {"multi juice","", gen("Drik",0,-15), 0.5}
items["æblejuice"] = {"æble juice","", gen("Drik",0,-15), 0.5}
items["appelsinjuice"] = {"appelsin juice","", gen("Drik",0,-15), 0.5}
items["jmilkshake"] = {"jordbær milkshake","", gen("Drik",0,-30), 0.5}
items["vmilkshake"] = {"vanilie milkshake","", gen("Drik",0,-30), 0.5}
items["jsaftevand"] = {"jordbær saftevand","", gen("Drik",0,-20), 0.5} 
items["csaftevand"] = {"cola saftevand","", gen("Drik",0,-20), 0.5} 
-- alkohol
items["vodka"] = {"Vodka","", gen("Drik",0,35),0.5}
items["grimbergen1"] = {"Grimbergen Blonde","", gen("Drik",0,10),0.2}
items["grimbergen2"] = {"Grimbergen Double Ambree","", gen("Drik",0,10),0.2}
items["grimbergen3"] = {"Grimbergen Blanche","", gen("Drik",0,10),0.2}
items["grimbergen4"] = {"Grimbergen Noel","", gen("Drik",0,10),0.2}
items["sighmirnoff"] = {"stærkt vodka","", gen("Drik",0,35),0.2}
items["smirhnhoff1"] = {"smirhnhoff ice","", gen("Drik",0,10),0.2}
items["gammeldansk"] = {"gammel dansk","", gen("Drik",0,35),0.2}
items["bacardilemon"] = {"bacardi lemon","", gen("Drik",0,35),0.2}
items["cubacaramel"] = {"cuba caramel","", gen("Drik",0,35),0.2}
items["slavevodka"] = {"slave vodka","", gen("Drik",0,35),0.2}
items["tuborgclassic"] = {"tuborg classic","", gen("Drik",0,10),0.2}
items["tuborgpilsner"] = {"tuborg pilsner","", gen("Drik",0,10),0.2}
items["carlsbergclassic"] = {"carlsberg classic","", gen("Drik",0,10),0.2}
items["carlsbergpilsner"] = {"carlsberg pilsner","", gen("Drik",0,10),0.2}
items["heiniken"] = {"heiniken","", gen("Drik",0,10),0.2}
items["cultchaker"] = {"cultchaker","", gen("Drik",0,10),0.2}
items["desmåblå"] = {"de små blå","", gen("Drik",0,10),0.2}
items["desmåsure"] = {"de små sure","", gen("Drik",0,35),0.2}
items["desmåsøde"] = {"de små søde","", gen("Drik",0,35),0.2}
items["desmågule"] = {"de små gule","", gen("Drik",0,35),0.2}
items["champange"] = {"champange","", gen("Drik",0,35),0.2}
items["byensvin"] = {"byensvin","", gen("Drik",0,25),0.2}
items["rødvin"] = {"rødvin","", gen("Drik",0,25),0.2}
items["hvidvin"] = {"hvidvin","", gen("Drik",0,25),0.2}
-- ingredienser
items["yougurt1"] = {"Banan og pærer yougurt","", gen("Spis",-25,-10),0.5}
items["yougurt2"] = {"Abrikos yougurt","", gen("Spis",-25,-10),0.5}
items["yougurt3"] = {"Blåbær yougurt","", gen("Spis",-25,-10),0.5}
items["Ymer"] = {"Ymer","", gen("Spis",-25,-10),0.5}
items["a38"] = {"A38","", gen("Spis",-25,-10),0.5}
-- grøntsager
items["tomat"] = {"Tomat","", gen("",0,0),0.5}
items["agurk"] = {"Agurk","", gen("",0,0),0.5}
items["rødløg"] = {"Rødløg","", gen("",0,0),0.5}
items["salathoved"] = {"Salathoved","", gen("",0,0),0.5}
items["rødpepper"] = {"Rød pepper","", gen("",0,0),0.5}
items["gulpepper"] = {"Gul pepper","", gen("",0,0),0.5}
items["grønpepper"] = {"Grøn pepper","", gen("",0,0),0.5}
items["radise"] = {"Radise","", gen("",0,0),0.5}
items["gullerød"] = {"Gullerød","", gen("",0,0),0.5}
-- andre mad varer
items["kartoffelsalat"] = {"Kartoffel salat","", gen("Spis",-45,10), 0.5}
items["hvidløgsbrød"] = {"Hvidløgs brød","", gen("Spis",-20,10), 0.5}
-- køkken retter
items["bread"] = {"Brød","", gen("Spis",-35,10),0.5}
items["ægbac"] = {"scrambled æg med bacon","", gen("Spis",-55,10),0.5}
items["salat1"] = {"Salat med hvidløgs dressing","", gen("Spis",-50,5),0.5}
items["lasange"] = {"Lasange","", gen("Spis",-65,10),0.5}
items["flæskesteg"] = {"Flæskesteg med kartofler og brun sovs","", gen("Spis",-75,10),0.5}
items["stægtflæsk"] = {"Stægt flæsk med persillesovs og kartofler","", gen("Spis",-70,10),0.5}
items["frikadeller"] = {"Frikadeller med kartofler og brun sovs","", gen("Spis",-70,10),0.5}
items["fiskefille"] = {"Fiskefille med pomfritter og remolade","", gen("Spis",-55,10),0.5}
items["kinagryde"] = {"stærk ret","", gen("Spis",-65,25),0.5}
items["pizza"] = {"hjemelavet pizza","", gen("Spis",-75,10),0.5}
items["pastalasange"] = {"Pasta lasange","", gen("Spis",-55,10),0.5}
items["bøf"] = {"Bøf med brun sovs, kartofler og bløde løg","", gen("Spis",-70,10),0.5}
items["bkærlighed"] = {"Brændende kærlighed","", gen("Spis",-60,10),0.5}
items["burger"] = {"Hjemmelavet burger","", gen("Spis",-65,10),0.5}
items["skinkeret"] = {"Skinke med kartofler og sovs","", gen("Spis",-60,10),0.5}
-- rugbrøds mader
items["ham"] = {"hambergryg mad","", gen("Spis",-20,5),0.5}
items["lever"] = {"leverposteg mad","", gen("Spis",-20,5),0.5}
items["kogt"] = {"kogt skinke mad","", gen("Spis",-20,5),0.5}
items["rul"] = {"rullepølse mad","", gen("Spis",-20,5),0.5}
-- kage
items["banankage"] = {"banankage","", gen("Spis",-25,0),0.5}
items["chokoladekage"] = {"chokoladekage","", gen("Spis",-25,0),0.5}
items["drømmekage"] = {"drømmekage","", gen("Spis",-25,0),0.5}
items["lagkage"] = {"lagkage","", gen("Spis",-25,0),0.5}
items["chokolademuffin"] = {"chokolade muffin","", gen("Spis",-25,0),0.5}
items["æblekage"] = {"æblekage","", gen("Spis",-25,0),0.5}
items["pdonut"] = {"Premium Donut","", gen("Spis",-15,0),0.5}
items["donut"] = {"Donut","", gen("Spis",-15,0),0.2}
-- fastfood
items["tacos"] = {"Tacos","", gen("Spis",-20,0),0.2}
items["sandwich"] = {"Sandwich","", gen("Spis",-25,0),0.5}
items["kebab"] = {"Kebab","", gen("Spis",-35,0),0.85}
items["pizza1"] = {"Margherita","", gen("Spis",-35,0),0.85}
items["pizza2"] = {"Vesuvio","", gen("Spis",-35,0),0.85}
items["pizza3"] = {"Capricciosa","", gen("Spis",-35,0),0.85}
items["pizza4"] = {"Hawaii","", gen("Spis",-35,0),0.85}
items["pizza5"] = {"Capone","", gen("Spis",-35,0),0.85}
items["pizza6"] = {"Italiano","", gen("Spis",-35,0),0.85}
items["pizza7"] = {"Luciano","", gen("Spis",-35,0),0.85}
items["pizza8"] = {"Europa","", gen("Spis",-35,0),0.85}
items["pizza9"] = {"Pepperoni","", gen("Spis",-35,0),0.85}
items["pizza10"] = {"Quattro Stagioni","", gen("Spis",-35,0),0.85}
items["pizza11"] = {"Calzone indbagt","", gen("Spis",-35,0),0.85}
items["pizza12"] = {"Spaghetti Indbagt","", gen("Spis",-35,0),0.85}
items["pizza13"] = {"Speciale","", gen("Spis",-35,0),0.85}
items["pizza14"] = {"Prins","", gen("Spis",-35,0),0.85}
items["pizza15"] = {"Super","", gen("Spis",-35,0),0.85}
items["pizza16"] = {"Arlecchino","", gen("Spis",-35,0),0.85}
items["pizza17"] = {"Pescatore","", gen("Spis",-35,0),0.85}
items["pizza18"] = {"Marinara","", gen("Spis",-35,0),0.85}
items["pizza19"] = {"Vegatarian","", gen("Spis",-35,0),0.85}
items["pizza20"] = {"kebab Pizza","", gen("Spis",-35,0),0.85}
items["pizza21"] = {"Kebab Rulle","", gen("Spis",-35,0),0.85}
items["pizza22"] = {"Miami","", gen("Spis",-35,0),0.85}
items["pizza23"] = {"Texas","", gen("Spis",-35,0),0.85}
items["pizza24"] = {"Las Vegas","", gen("Spis",-35,0),0.85}
items["pizza25"] = {"Denver","", gen("Spis",-35,0),0.85}
items["pizza26"] = {"Chicago","", gen("Spis",-35,0),0.85}
items["pizza27"] = {"Hawaii 1","", gen("Spis",-35,0),0.85}
items["pizza28"] = {"Mexico","", gen("Spis",-35,0),0.85}
items["pizza29"] = {"Vegatarian 1","", gen("Spis",-35,0),0.85}
items["pizza30"] = {"Florida","", gen("Spis",-35,0),0.85}
items["pizza31"] = {"LA","", gen("Spis",-35,0),0.85}
items["pizza32"] = {"Boston","", gen("Spis",-35,0),0.85}
items["pizza33"] = {"President","", gen("Spis",-35,0),0.85}
items["pizza34"] = {"Pizza Special","", gen("Spis",-35,0),0.85}
items["pizza35"] = {"Byens Pizza","", gen("Spis",-35,0),0.85}
items["pølsemix"] = {"Pølsemix","", gen("Spis",-25,0),0.5}
items["hotdog"] = {"hotdog","", gen("Spis",-25,0),0.5}
items["byensburger"] = {"Byens burger","", gen("Spis",-25,0),0.5}
items["doubleburger"] = {"Double burger","", gen("Spis",-25,0),0.5}
items["ribenstegsburger"] = {"Ribenstegs burger","", gen("Spis",-25,0),0.5}
items["kebabmix"] = {"Kebabmix","", gen("Spis",-25,0),0.5}
items["bondeburger"] = {"Bonde burger","", gen("Spis",-25,0),0.5}
items["brandburger"] = {"Brand burger","", gen("Spis",-25,0),0.5}
items["clasiskburger"] = {"Klasisk burger","", gen("Spis",-25,0),0.5}
items["fishnchips"] = {"Fish n chips","", gen("Spis",-10,35),0.5}
-- is
items["daimis"] = {"Daim is","", gen("Spis",-25,0),0.5}
items["børneis"] = {"Børne is","", gen("Spis",-25,0),0.5}
items["polariswaffelis"] = {"Polaris waffel is","", gen("Spis",-25,0),0.5}
items["deluxewaffelis"] = {"Deluxe waffel is","", gen("Spis",-25,0),0.5}
items["jordbærwaffelis"] = {"Jordbær waffel is","", gen("Spis",-25,0),0.5}
items["chokoladewaffelis"] = {"Chokolade waffel is","", gen("Spis",-25,0),0.5}
items["nøddewaffelis"] = {"nødde waffel is","", gen("Spis",-25,0),0.5}
-- frugt
items["æble"] = {"Æble","", gen("Spis",-5,0),0.5}
items["pærer"] = {"Pærer","", gen("Spis",-5,0),0.5}
items["mango"] = {"Mango","", gen("Spis",-5,0),0.5}
items["kiwi"] = {"Kiwi","", gen("Spis",-5,0),0.5}
items["vandmelon"] = {"Vand melon","", gen("Spis",-5,-10),0.5}
items["banan"] = {"Banan","", gen("Spis",-5,0),0.5}
items["jordbær"] = {"Jordbær","", gen("Spis",-5,0),0.5}
-- slik
items["chips"] = {"Chips","", gen("Spis",-10,0),0.5}
items["snikers"] = {"Snikers","", gen("Spis",-10,0),0.5}
items["haribod"] = {"Maribo dark mix","", gen("Spis",-10,0),0.5}
items["marsbar"] = {"Marsbar","", gen("Spis",-10,0),0.5}
items["hariboc"] = {"Maribo click mix","", gen("Spis",-10,0),0.5}
items["twix"] = {"Twix","", gen("Spis",-10,0),0.5}
items["Daim"] = {"Daim","", gen("Spis",-10,0),0.5}
